Feature: Login Functionality
  As a registered I should be able to login to my account so that I can use the modules.

  Scenario Outline: Verify that I can login with valid credentials as expensesmanager by clicking enter
    When User goes to application page
    And User enters valid "<email>" and "<password>" and clicks enter
    Then User lands on homepage as expensesmanager

    Examples:
      | email                       | password        |
      | expensesmanager10@info.com  | expensesmanager |
      | expensesmanager11@info.com  | expensesmanager |
      | expensesmanager12@info.com  | expensesmanager |
      | expensesmanager13@info.com  | expensesmanager |
      | expensesmanager14@info.com  | expensesmanager |
      | expensesmanager15@info.com  | expensesmanager |
      | expensesmanager16@info.com  | expensesmanager |
      | expensesmanager17@info.com  | expensesmanager |
      | expensesmanager18@info.com  | expensesmanager |
      | expensesmanager19@info.com  | expensesmanager |
      | expensesmanager20@info.com  | expensesmanager |
      | expensesmanager21@info.com  | expensesmanager |
      | expensesmanager22@info.com  | expensesmanager |
      | expensesmanager23@info.com  | expensesmanager |
      | expensesmanager24@info.com  | expensesmanager |
      | expensesmanager26@info.com  | expensesmanager |
      | expensesmanager27@info.com  | expensesmanager |
      | expensesmanager28@info.com  | expensesmanager |
      | expensesmanager29@info.com  | expensesmanager |
      | expensesmanager30@info.com  | expensesmanager |
      | expensesmanager31@info.com  | expensesmanager |
      | expensesmanager32@info.com  | expensesmanager |
      | expensesmanager33@info.com  | expensesmanager |
      | expensesmanager34@info.com  | expensesmanager |
      | expensesmanager35@info.com  | expensesmanager |
      | expensesmanager36@info.com  | expensesmanager |
      | expensesmanager37@info.com  | expensesmanager |
      | expensesmanager38@info.com  | expensesmanager |
      | expensesmanager39@info.com  | expensesmanager |
      | expensesmanager40@info.com  | expensesmanager |
      | expensesmanager41@info.com  | expensesmanager |
      | expensesmanager42@info.com  | expensesmanager |
      | expensesmanager43@info.com  | expensesmanager |
      | expensesmanager44@info.com  | expensesmanager |
      | expensesmanager45@info.com  | expensesmanager |
      | expensesmanager46@info.com  | expensesmanager |
      | expensesmanager47@info.com  | expensesmanager |
      | expensesmanager48@info.com  | expensesmanager |
      | expensesmanager49@info.com  | expensesmanager |
      | expensesmanager50@info.com  | expensesmanager |
      | expensesmanager51@info.com  | expensesmanager |
      | expensesmanager52@info.com  | expensesmanager |
      | expensesmanager53@info.com  | expensesmanager |
      | expensesmanager54@info.com  | expensesmanager |
      | expensesmanager55@info.com  | expensesmanager |
      | expensesmanager56@info.com  | expensesmanager |
      | expensesmanager57@info.com  | expensesmanager |
      | expensesmanager58@info.com  | expensesmanager |
      | expensesmanager59@info.com  | expensesmanager |
      | expensesmanager60@info.com  | expensesmanager |
      | expensesmanager61@info.com  | expensesmanager |
      | expensesmanager62@info.com  | expensesmanager |
      | expensesmanager63@info.com  | expensesmanager |
      | expensesmanager64@info.com  | expensesmanager |
      | expensesmanager65@info.com  | expensesmanager |
      | expensesmanager66@info.com  | expensesmanager |
      | expensesmanager67@info.com  | expensesmanager |
      | expensesmanager68@info.com  | expensesmanager |
      | expensesmanager69@info.com  | expensesmanager |
      | expensesmanager70@info.com  | expensesmanager |
      | expensesmanager71@info.com  | expensesmanager |
      | expensesmanager72@info.com  | expensesmanager |
      | expensesmanager73@info.com  | expensesmanager |
      | expensesmanager74@info.com  | expensesmanager |
      | expensesmanager75@info.com  | expensesmanager |
      | expensesmanager76@info.com  | expensesmanager |
      | expensesmanager77@info.com  | expensesmanager |
      | expensesmanager78@info.com  | expensesmanager |
      | expensesmanager79@info.com  | expensesmanager |
      | expensesmanager80@info.com  | expensesmanager |
      | expensesmanager81@info.com  | expensesmanager |
      | expensesmanager82@info.com  | expensesmanager |
      | expensesmanager83@info.com  | expensesmanager |
      | expensesmanager84@info.com  | expensesmanager |
      | expensesmanager85@info.com  | expensesmanager |
      | expensesmanager86@info.com  | expensesmanager |
      | expensesmanager87@info.com  | expensesmanager |
      | expensesmanager88@info.com  | expensesmanager |
      | expensesmanager89@info.com  | expensesmanager |
      | expensesmanager90@info.com  | expensesmanager |
      | expensesmanager91@info.com  | expensesmanager |
      | expensesmanager92@info.com  | expensesmanager |
      | expensesmanager93@info.com  | expensesmanager |
      | expensesmanager94@info.com  | expensesmanager |
      | expensesmanager95@info.com  | expensesmanager |
      | expensesmanager96@info.com  | expensesmanager |
      | expensesmanager97@info.com  | expensesmanager |
      | expensesmanager98@info.com  | expensesmanager |
      | expensesmanager99@info.com  | expensesmanager |
      | expensesmanager100@info.com | expensesmanager |
      | expensesmanager101@info.com | expensesmanager |
      | expensesmanager102@info.com | expensesmanager |
      | expensesmanager103@info.com | expensesmanager |
      | expensesmanager104@info.com | expensesmanager |
      | expensesmanager105@info.com | expensesmanager |
      | expensesmanager106@info.com | expensesmanager |
      | expensesmanager107@info.com | expensesmanager |
      | expensesmanager108@info.com | expensesmanager |
      | expensesmanager109@info.com | expensesmanager |
      | expensesmanager109@info.com | expensesmanager |
      | expensesmanager110@info.com | expensesmanager |


  Scenario Outline: Verify that I can login with valid credentials as expensesmanager by clicking enter
    When User goes to application page
    And User enters valid "<email>" and "<password>"
    And User clicks login button
    Then User lands on homepage as expensesmanager

    Examples:
      | email                       | password        |
      | expensesmanager10@info.com  | expensesmanager |
      | expensesmanager11@info.com  | expensesmanager |
      | expensesmanager12@info.com  | expensesmanager |
      | expensesmanager13@info.com  | expensesmanager |
      | expensesmanager14@info.com  | expensesmanager |
      | expensesmanager15@info.com  | expensesmanager |
      | expensesmanager16@info.com  | expensesmanager |
      | expensesmanager17@info.com  | expensesmanager |
      | expensesmanager18@info.com  | expensesmanager |
      | expensesmanager19@info.com  | expensesmanager |
      | expensesmanager20@info.com  | expensesmanager |
      | expensesmanager21@info.com  | expensesmanager |
      | expensesmanager22@info.com  | expensesmanager |
      | expensesmanager23@info.com  | expensesmanager |
      | expensesmanager24@info.com  | expensesmanager |
      | expensesmanager26@info.com  | expensesmanager |
      | expensesmanager27@info.com  | expensesmanager |
      | expensesmanager28@info.com  | expensesmanager |
      | expensesmanager29@info.com  | expensesmanager |
      | expensesmanager30@info.com  | expensesmanager |
      | expensesmanager31@info.com  | expensesmanager |
      | expensesmanager32@info.com  | expensesmanager |
      | expensesmanager33@info.com  | expensesmanager |
      | expensesmanager34@info.com  | expensesmanager |
      | expensesmanager35@info.com  | expensesmanager |
      | expensesmanager36@info.com  | expensesmanager |
      | expensesmanager37@info.com  | expensesmanager |
      | expensesmanager38@info.com  | expensesmanager |
      | expensesmanager39@info.com  | expensesmanager |
      | expensesmanager40@info.com  | expensesmanager |
      | expensesmanager41@info.com  | expensesmanager |
      | expensesmanager42@info.com  | expensesmanager |
      | expensesmanager43@info.com  | expensesmanager |
      | expensesmanager44@info.com  | expensesmanager |
      | expensesmanager45@info.com  | expensesmanager |
      | expensesmanager46@info.com  | expensesmanager |
      | expensesmanager47@info.com  | expensesmanager |
      | expensesmanager48@info.com  | expensesmanager |
      | expensesmanager49@info.com  | expensesmanager |
      | expensesmanager50@info.com  | expensesmanager |
      | expensesmanager51@info.com  | expensesmanager |
      | expensesmanager52@info.com  | expensesmanager |
      | expensesmanager53@info.com  | expensesmanager |
      | expensesmanager54@info.com  | expensesmanager |
      | expensesmanager55@info.com  | expensesmanager |
      | expensesmanager56@info.com  | expensesmanager |
      | expensesmanager57@info.com  | expensesmanager |
      | expensesmanager58@info.com  | expensesmanager |
      | expensesmanager59@info.com  | expensesmanager |
      | expensesmanager60@info.com  | expensesmanager |
      | expensesmanager61@info.com  | expensesmanager |
      | expensesmanager62@info.com  | expensesmanager |
      | expensesmanager63@info.com  | expensesmanager |
      | expensesmanager64@info.com  | expensesmanager |
      | expensesmanager65@info.com  | expensesmanager |
      | expensesmanager66@info.com  | expensesmanager |
      | expensesmanager67@info.com  | expensesmanager |
      | expensesmanager68@info.com  | expensesmanager |
      | expensesmanager69@info.com  | expensesmanager |
      | expensesmanager70@info.com  | expensesmanager |
      | expensesmanager71@info.com  | expensesmanager |
      | expensesmanager72@info.com  | expensesmanager |
      | expensesmanager73@info.com  | expensesmanager |
      | expensesmanager74@info.com  | expensesmanager |
      | expensesmanager75@info.com  | expensesmanager |
      | expensesmanager76@info.com  | expensesmanager |
      | expensesmanager77@info.com  | expensesmanager |
      | expensesmanager78@info.com  | expensesmanager |
      | expensesmanager79@info.com  | expensesmanager |
      | expensesmanager80@info.com  | expensesmanager |
      | expensesmanager81@info.com  | expensesmanager |
      | expensesmanager82@info.com  | expensesmanager |
      | expensesmanager83@info.com  | expensesmanager |
      | expensesmanager84@info.com  | expensesmanager |
      | expensesmanager85@info.com  | expensesmanager |
      | expensesmanager86@info.com  | expensesmanager |
      | expensesmanager87@info.com  | expensesmanager |
      | expensesmanager88@info.com  | expensesmanager |
      | expensesmanager89@info.com  | expensesmanager |
      | expensesmanager90@info.com  | expensesmanager |
      | expensesmanager91@info.com  | expensesmanager |
      | expensesmanager92@info.com  | expensesmanager |
      | expensesmanager93@info.com  | expensesmanager |
      | expensesmanager94@info.com  | expensesmanager |
      | expensesmanager95@info.com  | expensesmanager |
      | expensesmanager96@info.com  | expensesmanager |
      | expensesmanager97@info.com  | expensesmanager |
      | expensesmanager98@info.com  | expensesmanager |
      | expensesmanager99@info.com  | expensesmanager |
      | expensesmanager100@info.com | expensesmanager |
      | expensesmanager101@info.com | expensesmanager |
      | expensesmanager102@info.com | expensesmanager |
      | expensesmanager103@info.com | expensesmanager |
      | expensesmanager104@info.com | expensesmanager |
      | expensesmanager105@info.com | expensesmanager |
      | expensesmanager106@info.com | expensesmanager |
      | expensesmanager107@info.com | expensesmanager |
      | expensesmanager108@info.com | expensesmanager |
      | expensesmanager109@info.com | expensesmanager |
      | expensesmanager109@info.com | expensesmanager |
      | expensesmanager110@info.com | expensesmanager |

