Feature: Login Functionality
  As a registered I should be able to login to my account so that I can use the modules.

  Scenario Outline: Verify that I can login with valid credentials as inventorymanager by clicking enter
    When User goes to application page
    And User enters valid "<email>" and "<password>" and clicks enter
    Then User lands on homepage as inventorymanager

    Examples:
      | email           | password |
      | imm10@info.com  | inventorymanager      |
      | imm11@info.com  | inventorymanager      |
      | imm12@info.com  | inventorymanager      |
      | imm13@info.com  | inventorymanager      |
      | imm14@info.com  | inventorymanager      |
      | imm15@info.com  | inventorymanager      |
      | imm16@info.com  | inventorymanager      |
      | imm17@info.com  | inventorymanager      |
      | imm18@info.com  | inventorymanager      |
      | imm19@info.com  | inventorymanager      |
      | imm20@info.com  | inventorymanager      |
      | imm21@info.com  | inventorymanager      |
      | imm22@info.com  | inventorymanager      |
      | imm23@info.com  | inventorymanager      |
      | imm24@info.com  | inventorymanager      |
      | imm26@info.com  | inventorymanager      |
      | imm27@info.com  | inventorymanager      |
      | imm28@info.com  | inventorymanager      |
      | imm29@info.com  | inventorymanager      |
      | imm30@info.com  | inventorymanager      |
      | imm31@info.com  | inventorymanager      |
      | imm32@info.com  | inventorymanager      |
      | imm33@info.com  | inventorymanager      |
      | imm34@info.com  | inventorymanager      |
      | imm35@info.com  | inventorymanager      |
      | imm36@info.com  | inventorymanager      |
      | imm37@info.com  | inventorymanager      |
      | imm38@info.com  | inventorymanager      |
      | imm39@info.com  | inventorymanager      |
      | imm40@info.com  | inventorymanager      |
      | imm41@info.com  | inventorymanager      |
      | imm42@info.com  | inventorymanager      |
      | imm43@info.com  | inventorymanager      |
      | imm44@info.com  | inventorymanager      |
      | imm45@info.com  | inventorymanager      |
      | imm46@info.com  | inventorymanager      |
      | imm47@info.com  | inventorymanager      |
      | imm48@info.com  | inventorymanager      |
      | imm49@info.com  | inventorymanager      |
      | imm50@info.com  | inventorymanager      |
      | imm51@info.com  | inventorymanager      |
      | imm52@info.com  | inventorymanager      |
      | imm53@info.com  | inventorymanager      |
      | imm54@info.com  | inventorymanager      |
      | imm55@info.com  | inventorymanager      |
      | imm56@info.com  | inventorymanager      |
      | imm57@info.com  | inventorymanager      |
      | imm58@info.com  | inventorymanager      |
      | imm59@info.com  | inventorymanager      |
      | imm60@info.com  | inventorymanager      |
      | imm61@info.com  | inventorymanager      |
      | imm62@info.com  | inventorymanager      |
      | imm63@info.com  | inventorymanager      |
      | imm64@info.com  | inventorymanager      |
      | imm65@info.com  | inventorymanager      |
      | imm66@info.com  | inventorymanager      |
      | imm67@info.com  | inventorymanager      |
      | imm68@info.com  | inventorymanager      |
      | imm69@info.com  | inventorymanager      |
      | imm70@info.com  | inventorymanager      |
      | imm71@info.com  | inventorymanager      |
      | imm72@info.com  | inventorymanager      |
      | imm73@info.com  | inventorymanager      |
      | imm74@info.com  | inventorymanager      |
      | imm75@info.com  | inventorymanager      |
      | imm76@info.com  | inventorymanager      |
      | imm77@info.com  | inventorymanager      |
      | imm78@info.com  | inventorymanager      |
      | imm79@info.com  | inventorymanager      |
      | imm80@info.com  | inventorymanager      |
      | imm81@info.com  | inventorymanager      |
      | imm82@info.com  | inventorymanager      |
      | imm83@info.com  | inventorymanager      |
      | imm84@info.com  | inventorymanager      |
      | imm85@info.com  | inventorymanager      |
      | imm86@info.com  | inventorymanager      |
      | imm87@info.com  | inventorymanager      |
      | imm88@info.com  | inventorymanager      |
      | imm89@info.com  | inventorymanager      |
      | imm90@info.com  | inventorymanager      |
      | imm91@info.com  | inventorymanager      |
      | imm92@info.com  | inventorymanager      |
      | imm93@info.com  | inventorymanager      |
      | imm94@info.com  | inventorymanager      |
      | imm95@info.com  | inventorymanager      |
      | imm96@info.com  | inventorymanager      |
      | imm97@info.com  | inventorymanager      |
      | imm98@info.com  | inventorymanager      |
      | imm99@info.com  | inventorymanager      |
      | imm100@info.com | inventorymanager      |
      | imm101@info.com | inventorymanager      |
      | imm102@info.com | inventorymanager      |
      | imm103@info.com | inventorymanager      |
      | imm104@info.com | inventorymanager      |
      | imm105@info.com | inventorymanager      |
      | imm106@info.com | inventorymanager      |
      | imm107@info.com | inventorymanager     |
      | imm108@info.com | inventorymanager      |
      | imm109@info.com | inventorymanager      |
      | imm109@info.com | inventorymanager      |
      | imm110@info.com | inventorymanager      |
      | imm111@info.com | inventorymanager      |
      | imm112@info.com | inventorymanager      |
      | imm113@info.com | inventorymanager      |
      | imm114@info.com | inventorymanager      |
      | imm115@info.com | inventorymanager      |
      | imm116@info.com | inventorymanager      |
      | imm117@info.com | inventorymanager      |
      | imm118@info.com | inventorymanager      |
      | imm119@info.com | inventorymanager      |
      | imm120@info.com | inventorymanager      |
      | imm121@info.com | inventorymanager      |
      | imm122@info.com | inventorymanager      |
      | imm123@info.com | inventorymanager      |
      | imm124@info.com | inventorymanager      |
      | imm125@info.com | inventorymanager      |
      | imm126@info.com | inventorymanager      |
      | imm127@info.com | inventorymanager      |
      | imm128@info.com | inventorymanager      |
      | imm129@info.com | inventorymanager      |
      | imm130@info.com | inventorymanager      |
      | imm131@info.com | inventorymanager      |
      | imm132@info.com | inventorymanager      |
      | imm133@info.com | inventorymanager      |
      | imm134@info.com | inventorymanager      |
      | imm135@info.com | inventorymanager      |
      | imm136@info.com | inventorymanager      |
      | imm137@info.com | inventorymanager      |
      | imm138@info.com | inventorymanager      |
      | imm139@info.com | inventorymanager      |
      | imm140@info.com | inventorymanager      |
      | imm141@info.com | inventorymanager      |
      | imm142@info.com | inventorymanager      |
      | imm143@info.com | inventorymanager      |
      | imm144@info.com | inventorymanager      |
      | imm145@info.com | inventorymanager      |
      | imm146@info.com | inventorymanager      |
      | imm147@info.com | inventorymanager      |
      | imm148@info.com | inventorymanager      |
      | imm149@info.com | inventorymanager      |
      | imm150@info.com | inventorymanager      |
      | imm151@info.com | inventorymanager      |
      | imm152@info.com | inventorymanager      |
      | imm153@info.com | inventorymanager      |
      | imm154@info.com | inventorymanager      |
      | imm155@info.com | inventorymanager      |
      | imm156@info.com | inventorymanager      |
      | imm157@info.com | inventorymanager      |
      | imm158@info.com | inventorymanager      |
      | imm159@info.com | inventorymanager      |
      | imm160@info.com | inventorymanager      |


  Scenario Outline: Verify that I can login with valid credentials as inventorymanager by clicking enter
    When User goes to application page
    And User enters valid "<email>" and "<password>"
    And User clicks login button
    Then User lands on homepage as inventorymanager

    Examples:
      | email           | password |
      | imm10@info.com  | inventorymanager      |
      | imm11@info.com  | inventorymanager      |
      | imm12@info.com  | inventorymanager      |
      | imm13@info.com  | inventorymanager      |
      | imm14@info.com  | inventorymanager      |
      | imm15@info.com  | inventorymanager      |
      | imm16@info.com  | inventorymanager      |
      | imm17@info.com  | inventorymanager      |
      | imm18@info.com  | inventorymanager      |
      | imm19@info.com  | inventorymanager      |
      | imm20@info.com  | inventorymanager      |
      | imm21@info.com  | inventorymanager      |
      | imm22@info.com  | inventorymanager      |
      | imm23@info.com  | inventorymanager      |
      | imm24@info.com  | inventorymanager      |
      | imm26@info.com  | inventorymanager      |
      | imm27@info.com  | inventorymanager      |
      | imm28@info.com  | inventorymanager      |
      | imm29@info.com  | inventorymanager      |
      | imm30@info.com  | inventorymanager      |
      | imm31@info.com  | inventorymanager      |
      | imm32@info.com  | inventorymanager      |
      | imm33@info.com  | inventorymanager      |
      | imm34@info.com  | inventorymanager      |
      | imm35@info.com  | inventorymanager      |
      | imm36@info.com  | inventorymanager      |
      | imm37@info.com  | inventorymanager      |
      | imm38@info.com  | inventorymanager      |
      | imm39@info.com  | inventorymanager      |
      | imm40@info.com  | inventorymanager      |
      | imm41@info.com  | inventorymanager      |
      | imm42@info.com  | inventorymanager      |
      | imm43@info.com  | inventorymanager      |
      | imm44@info.com  | inventorymanager      |
      | imm45@info.com  | inventorymanager      |
      | imm46@info.com  | inventorymanager      |
      | imm47@info.com  | inventorymanager      |
      | imm48@info.com  | inventorymanager      |
      | imm49@info.com  | inventorymanager      |
      | imm50@info.com  | inventorymanager      |
      | imm51@info.com  | inventorymanager      |
      | imm52@info.com  | inventorymanager      |
      | imm53@info.com  | inventorymanager      |
      | imm54@info.com  | inventorymanager      |
      | imm55@info.com  | inventorymanager      |
      | imm56@info.com  | inventorymanager      |
      | imm57@info.com  | inventorymanager      |
      | imm58@info.com  | inventorymanager      |
      | imm59@info.com  | inventorymanager      |
      | imm60@info.com  | inventorymanager      |
      | imm61@info.com  | inventorymanager      |
      | imm62@info.com  | inventorymanager      |
      | imm63@info.com  | inventorymanager      |
      | imm64@info.com  | inventorymanager      |
      | imm65@info.com  | inventorymanager      |
      | imm66@info.com  | inventorymanager      |
      | imm67@info.com  | inventorymanager      |
      | imm68@info.com  | inventorymanager      |
      | imm69@info.com  | inventorymanager      |
      | imm70@info.com  | inventorymanager      |
      | imm71@info.com  | inventorymanager      |
      | imm72@info.com  | inventorymanager      |
      | imm73@info.com  | inventorymanager      |
      | imm74@info.com  | inventorymanager      |
      | imm75@info.com  | inventorymanager      |
      | imm76@info.com  | inventorymanager      |
      | imm77@info.com  | inventorymanager      |
      | imm78@info.com  | inventorymanager      |
      | imm79@info.com  | inventorymanager      |
      | imm80@info.com  | inventorymanager      |
      | imm81@info.com  | inventorymanager      |
      | imm82@info.com  | inventorymanager      |
      | imm83@info.com  | inventorymanager      |
      | imm84@info.com  | inventorymanager      |
      | imm85@info.com  | inventorymanager      |
      | imm86@info.com  | inventorymanager      |
      | imm87@info.com  | inventorymanager      |
      | imm88@info.com  | inventorymanager      |
      | imm89@info.com  | inventorymanager      |
      | imm90@info.com  | inventorymanager      |
      | imm91@info.com  | inventorymanager      |
      | imm92@info.com  | inventorymanager      |
      | imm93@info.com  | inventorymanager      |
      | imm94@info.com  | inventorymanager      |
      | imm95@info.com  | inventorymanager      |
      | imm96@info.com  | inventorymanager      |
      | imm97@info.com  | inventorymanager      |
      | imm98@info.com  | inventorymanager      |
      | imm99@info.com  | inventorymanager      |
      | imm100@info.com | inventorymanager      |
      | imm101@info.com | inventorymanager      |
      | imm102@info.com | inventorymanager      |
      | imm103@info.com | inventorymanager      |
      | imm104@info.com | inventorymanager      |
      | imm105@info.com | inventorymanager      |
      | imm106@info.com | inventorymanager      |
      | imm107@info.com | inventorymanager     |
      | imm108@info.com | inventorymanager      |
      | imm109@info.com | inventorymanager      |
      | imm109@info.com | inventorymanager      |
      | imm110@info.com | inventorymanager      |
      | imm111@info.com | inventorymanager      |
      | imm112@info.com | inventorymanager      |
      | imm113@info.com | inventorymanager      |
      | imm114@info.com | inventorymanager      |
      | imm115@info.com | inventorymanager      |
      | imm116@info.com | inventorymanager      |
      | imm117@info.com | inventorymanager      |
      | imm118@info.com | inventorymanager      |
      | imm119@info.com | inventorymanager      |
      | imm120@info.com | inventorymanager      |
      | imm121@info.com | inventorymanager      |
      | imm122@info.com | inventorymanager      |
      | imm123@info.com | inventorymanager      |
      | imm124@info.com | inventorymanager      |
      | imm125@info.com | inventorymanager      |
      | imm126@info.com | inventorymanager      |
      | imm127@info.com | inventorymanager      |
      | imm128@info.com | inventorymanager      |
      | imm129@info.com | inventorymanager      |
      | imm130@info.com | inventorymanager      |
      | imm131@info.com | inventorymanager      |
      | imm132@info.com | inventorymanager      |
      | imm133@info.com | inventorymanager      |
      | imm134@info.com | inventorymanager      |
      | imm135@info.com | inventorymanager      |
      | imm136@info.com | inventorymanager      |
      | imm137@info.com | inventorymanager      |
      | imm138@info.com | inventorymanager      |
      | imm139@info.com | inventorymanager      |
      | imm140@info.com | inventorymanager      |
      | imm141@info.com | inventorymanager      |
      | imm142@info.com | inventorymanager      |
      | imm143@info.com | inventorymanager      |
      | imm144@info.com | inventorymanager      |
      | imm145@info.com | inventorymanager      |
      | imm146@info.com | inventorymanager      |
      | imm147@info.com | inventorymanager      |
      | imm148@info.com | inventorymanager      |
      | imm149@info.com | inventorymanager      |
      | imm150@info.com | inventorymanager      |
      | imm151@info.com | inventorymanager      |
      | imm152@info.com | inventorymanager      |
      | imm153@info.com | inventorymanager      |
      | imm154@info.com | inventorymanager      |
      | imm155@info.com | inventorymanager      |
      | imm156@info.com | inventorymanager      |
      | imm157@info.com | inventorymanager      |
      | imm158@info.com | inventorymanager      |
      | imm159@info.com | inventorymanager      |
      | imm160@info.com | inventorymanager      |