Feature: Login Functionality
  As a registered I should be able to login to my account so that I can use the modules.

  @wip
  Scenario Outline: Verify that I can login with valid credentials as manufacturing user by clicking enter
    When User goes to application page
    And User enters valid "<email>" and "<password>" and clicks enter
    Then User lands on homepage as manufacturing user

    Examples:
      | email                  | password  |
      | manuf_user10@info.com  | manufuser |
      | manuf_user11@info.com  | manufuser |
      | manuf_user12@info.com  | manufuser |
      | manuf_user13@info.com  | manufuser |
      | manuf_user14@info.com  | manufuser |
      | manuf_user15@info.com  | manufuser |
      | manuf_user16@info.com  | manufuser |
      | manuf_user17@info.com  | manufuser |
      | manuf_user18@info.com  | manufuser |
      | manuf_user19@info.com  | manufuser |
      | manuf_user20@info.com  | manufuser |
      | manuf_user21@info.com  | manufuser |
      | manuf_user22@info.com  | manufuser |
      | manuf_user23@info.com  | manufuser |
      | manuf_user24@info.com  | manufuser |
      | manuf_user26@info.com  | manufuser |
      | manuf_user27@info.com  | manufuser |
      | manuf_user28@info.com  | manufuser |
      | manuf_user29@info.com  | manufuser |
      | manuf_user30@info.com  | manufuser |
      | manuf_user31@info.com  | manufuser |
      | manuf_user32@info.com  | manufuser |
      | manuf_user33@info.com  | manufuser |
      | manuf_user34@info.com  | manufuser |
      | manuf_user35@info.com  | manufuser |
      | manuf_user36@info.com  | manufuser |
      | manuf_user37@info.com  | manufuser |
      | manuf_user38@info.com  | manufuser |
      | manuf_user39@info.com  | manufuser |
      | manuf_user40@info.com  | manufuser |
      | manuf_user41@info.com  | manufuser |
      | manuf_user42@info.com  | manufuser |
      | manuf_user43@info.com  | manufuser |
      | manuf_user44@info.com  | manufuser |
      | manuf_user45@info.com  | manufuser |
      | manuf_user46@info.com  | manufuser |
      | manuf_user47@info.com  | manufuser |
      | manuf_user48@info.com  | manufuser |
      | manuf_user49@info.com  | manufuser |
      | manuf_user50@info.com  | manufuser |
      | manuf_user51@info.com  | manufuser |
      | manuf_user52@info.com  | manufuser |
      | manuf_user53@info.com  | manufuser |
      | manuf_user54@info.com  | manufuser |
      | manuf_user55@info.com  | manufuser |
      | manuf_user56@info.com  | manufuser |
      | manuf_user57@info.com  | manufuser |
      | manuf_user58@info.com  | manufuser |
      | manuf_user59@info.com  | manufuser |
      | manuf_user60@info.com  | manufuser |
      | manuf_user61@info.com  | manufuser |
      | manuf_user62@info.com  | manufuser |
      | manuf_user63@info.com  | manufuser |
      | manuf_user64@info.com  | manufuser |
      | manuf_user65@info.com  | manufuser |
      | manuf_user66@info.com  | manufuser |
      | manuf_user67@info.com  | manufuser |
      | manuf_user68@info.com  | manufuser |
      | manuf_user69@info.com  | manufuser |
      | manuf_user70@info.com  | manufuser |
      | manuf_user71@info.com  | manufuser |
      | manuf_user72@info.com  | manufuser |
      | manuf_user73@info.com  | manufuser |
      | manuf_user74@info.com  | manufuser |
      | manuf_user75@info.com  | manufuser |
      | manuf_user76@info.com  | manufuser |
      | manuf_user77@info.com  | manufuser |
      | manuf_user78@info.com  | manufuser |
      | manuf_user79@info.com  | manufuser |
      | manuf_user80@info.com  | manufuser |
      | manuf_user81@info.com  | manufuser |
      | manuf_user82@info.com  | manufuser |
      | manuf_user83@info.com  | manufuser |
      | manuf_user84@info.com  | manufuser |
      | manuf_user85@info.com  | manufuser |
      | manuf_user86@info.com  | manufuser |
      | manuf_user87@info.com  | manufuser |
      | manuf_user88@info.com  | manufuser |
      | manuf_user89@info.com  | manufuser |
      | manuf_user90@info.com  | manufuser |
      | manuf_user91@info.com  | manufuser |
      | manuf_user92@info.com  | manufuser |
      | manuf_user93@info.com  | manufuser |
      | manuf_user94@info.com  | manufuser |
      | manuf_user95@info.com  | manufuser |
      | manuf_user96@info.com  | manufuser |
      | manuf_user97@info.com  | manufuser |
      | manuf_user98@info.com  | manufuser |
      | manuf_user99@info.com  | manufuser |
      | manuf_user100@info.com | manufuser |
      | manuf_user101@info.com | manufuser |
      | manuf_user102@info.com | manufuser |
      | manuf_user103@info.com | manufuser |
      | manuf_user104@info.com | manufuser |
      | manuf_user105@info.com | manufuser |
      | manuf_user106@info.com | manufuser |
      | manuf_user107@info.com | manufuser |
      | manuf_user108@info.com | manufuser |
      | manuf_user109@info.com | manufuser |
      | manuf_user109@info.com | manufuser |
      | manuf_user110@info.com | manufuser |
